apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default  # Replace with your namespace if necessary
data:
  prometheus.yml: |
    # Your Prometheus configuration here (the same content as the file you provided)
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["localhost:9093"]
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "junjie-flask-app"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["junjie-flask-metrics:31327"]
      - job_name: "node_exporter"
        static_configs:
          - targets: ["node_exporter:9100"]
      - job_name: "cadvisor"
        static_configs:
          - targets: ["cadvisor:8080"]
